data=input("Enter a string:")
x=slice(7)
print(data)
print(data[x])
print(data.capitalize())
print(data.title())
print(data.upper())
print(data.lower())
print(data.strip())
print(data.find("world"))
print(data.count("hello"))
print(data.replace("hello","hi"))
x="abc"
print(data())
print(x[:2])
print(len(data))
print(data[::-1])

