import hwcalmodule as cal
n1=int(input("enter:"))
n2=int(input("enter:"))
print(cal.add(n1,n2))
print(cal.sub(n1,n2))
print(cal.mul(n1,n2))
print(cal.div(n1,n2))
print(cal.floordiv(n1,n2))
print(cal.exp(n1,n2))
print(cal.mod(n1,n2))