data=input("enter the string:")
x=slice(3)
print(data)
print(data[x])
print(data.capitalize())
print(data.title())
print(data.upper())
print(data.lower())
print(data.strip())
print(data.find("world"))
print(data.replace("hello","hii"))#replace
print(len(data))
#(data[len(data)-1])
print(data[-1])
#print(data[22])
print(data[1:4])
print(data[::-1])# reversing
